feat: added sign up page
i-am-a-codegirl/Snack-it-ecommerceSite pull request #7
Opened 2022-03-26 15:05 UTC by i-am-a-codegirl

Kindly review my home page for the eCommerce website

The page has the following features

1. Nav : has brand name and links to home, all-products, login, cart and wishlist page
2. Contains username field along with password field & button to help user sign-out
3. Footer : contains links to login, all-products, category. etc

![image](https://user-images.githubusercontent.com/81037395/160245453-506c1701-6fb2-416d-a252-e5f6a6e166f1.png)

2022-03-26 15:09 UTC, khushijohri2001 requested changes
Do add First Name, Last Name and Confirm Password fields too

2022-03-27 04:31 UTC, sahiba0915 approved these changes
good to go, just remove unwanted spaces and give proper title

2022-03-27 06:38 UTC, i-am-a-codegirl commented
> Do add First Name, Last Name and Confirm Password fields too

sure will do

2022-03-27 06:52 UTC, khushijohri2001 approved these changes

2022-03-27 07:03 UTC, merged